server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: springboot-webmvc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    converters:
      preferred-json-mapper: protobuf

logging:
  level:
    root: INFO
    com.example.springbootwebmvc: DEBUG 